AWSTemplateFormatVersion: "2010-09-09"
Outputs:
  GatewayId:
    Value:
      Ref: Gateway
Resources:
  ElasticIP:
    Type: AWS::EC2::EIP
  Gateway:
    Properties:
      AutoAcceptSharedAttachments: enable
      DefaultRouteTableAssociation: disable
      DefaultRouteTablePropagation: disable
      Description: Transit gateway for dev-coreNetwork
      DnsSupport: enable
      VpnEcmpSupport: disable
    Type: AWS::EC2::TransitGateway
